### ISSUE TITLE
Have you thought about open source the segment api souce code?

### ISSUE THREAD

**Issue by xiakeng** [endrl/jellyfin-plugin-media-analyzer#5]
**Describe the feature you'd like added**
I'm having some errors in media analyzer and edl creator.
e.g. 
[2024-01-21 23:17:40.606 +00:00] [INF] [37] Jellyfin.Plugin.MediaAnalyzer.Plugin: No 'Intro' segment found for '"Pantheon S-1: The Gods Will Not Be Slain"', blacklist for future analysis
[2024-01-21 23:17:40.607 +00:00] [ERR] [3] Emby.Server.Implementations.ScheduledTasks.TaskManager: Error executing Scheduled Task
System.AggregateException: One or more errors occurred. (One or more errors occurred. (start >= end: 0>=0 for segment itemId 'fab1a1e7-fa6c-8111-6ddc-8e793261b4e0' with type 'Intro.0'))
 ---> System.AggregateException: One or more errors occurred. (start >= end: 0>=0 for segment itemId 'fab1a1e7-fa6c-8111-6ddc-8e793261b4e0' with type 'Intro.0')
 ---> System.ArgumentException: start >= end: 0>=0 for segment itemId 'fab1a1e7-fa6c-8111-6ddc-8e793261b4e0' with type 'Intro.0'
   at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentsManager.ValidateSegment(MediaSegment segment)
   at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentsManager.CreateMediaSegmentsAsync(IEnumerable`1 segments)
   at Jellyfin.Server.Implementations.MediaSegments.MediaSegmentsManager.CreateMediaSegmentsAsync(IEnumerable`1 segments)
   at Jellyfin.Plugin.MediaAnalyzer.Plugin.SaveSegmentsAsync(Dictionary`2 segments, AnalysisMode mode)
   at Jellyfin.Plugin.MediaAnalyzer.Plugin.<>c__DisplayClass49_0.<<UpdateTimestamps>b__0>d.MoveNext()

I understand this is per-content error might be difficult for you to fix.
I'd like to contribute, but I can just add extracted dlls as package reference and debug through log only.
Without jellyfin server source code with segment api, I have no idea how to debug directly using IDE.
It's quite difficult to debug only based on logs

**Additional context**
If you have reason not to open source it, I can understand. I can still debug thru log.

**Comment by sammy-ette** [comment]
https://github.com/endrl/jellyfin/tree/mediasegments it's already open source, kinda has to be. There's already a PR open for it on Jellyfin, you would've found that too if you did some searching.

**Comment by xiakeng** [comment]
ah, right.
sorry I missed that one.
thx
